### ISSUE TITLE
Keep getting  Method not found: 'System.Object Akka.Persistence.SnapshotOffer.get_Snapshot()'. when trying to read from snapshot offer

### ISSUE THREAD

**Issue by diegolinan** [AkkaNetContrib/Akka.Persistence.MongoDB#32]
Snapshots are being saved just fine, but I get this error every time I try to get the snapshot offer from Mongo.

All my message classes are registered using BsonClassMap.RegisterClassMap. I even tried to register SnapshotMetadata and SnapshotOffer just to try something else out but nothing. Keep getting the same error:

[ERROR][12/3/2017 5:36:21 p. m.][Thread 0003][akka://UserManagerActorSystem/user/UserManagerActor/srv_qatoolstester] Method not found: 'System.Object Akka.Persistence.SnapshotOffer.get_Snapshot()'.
Cause: System.MissingMethodException: Method not found: 'System.Object Akka.Persistence.SnapshotOffer.get_Snapshot()'.
   at Moravia.Ahoj.Server.System.Users.Actors.UserActor.<Ready>b__5_8(SnapshotOffer offer)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Persistence.ReceivePersistentActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Persistence.ReceivePersistentActor.OnRecover(Object message)
   at Akka.Persistence.UntypedPersistentActor.ReceiveRecover(Object message)
   at Akka.Persistence.Eventsourced.<RecoveryStarted>b__88_0(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Persistence.Eventsourced.<>c__DisplayClass88_0.<RecoveryStarted>b__1(Receive receive, Object message)
   at Akka.Persistence.Eventsourced.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

Here is my hocon file configuration. Very simple:

        persistence 
        {
          publish-plugin-commands = on
          
          journal 
          {
            plugin = "akka.persistence.journal.mongodb"
            mongodb 
            {
              class = "Akka.Persistence.MongoDb.Journal.MongoDbJournal, Akka.Persistence.MongoDb"
              connection-string = "mongodb://localhost/EventStore"
              collection = "EventJournal"
              metadata-collection = "Metadata"
              auto-initialize = on
              plugin-dispatcher = "akka.actor.default-dispatcher"
            }
          }

          snapshot-store 
          {
            plugin = "akka.persistence.snapshot-store.mongodb"
            mongodb 
            {
              class = "Akka.Persistence.MongoDb.Snapshot.MongoDbSnapshotStore, Akka.Persistence.MongoDb"
              connection-string = "mongodb://localhost/EventStore"
              collection = "SnapshotStore"
              auto-initialize = on
              plugin-dispatcher = "akka.actor.default-dispatcher"
            }
          }
        }

Events are replayed OK. The only problem seems to be when trying to read the snapshot offer

**Comment by diegolinan** [comment]
Had to use an older version of Akks.Persistence
